CREATE TABLE IF NOT EXISTS CG_CostMatrixRules (
    rule_id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    min_price     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    max_price     DECIMAL(10,2) DEFAULT NULL,
    pct_rate      DECIMAL(5,2)  NOT NULL DEFAULT 0.00,
    fixed_cost    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    minimum_cost  DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    display_order TINYINT UNSIGNED NOT NULL DEFAULT 0,
    is_active     TINYINT(1) NOT NULL DEFAULT 1,
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
