-- Card Graph - Parser Support Seed Data
-- Migration 011: Players (top MLB prospects), expanded CardMakers, CardStyles, CardSpecialties
-- Generated: 2026-02-21
-- Sources: JustBaseball Top 100 (2026), FanGraphs Top 100 (2026), ESPN 101-200 (2026)

-- ============================================================
-- 1. CG_Players - Top MLB Prospects (2025-2026)
-- ============================================================
-- Merged from multiple prospect lists; ~150 players covering
-- the most card-traded minor leaguers across all 30 organizations.

INSERT IGNORE INTO CG_Players (first_name, last_name, primary_position) VALUES
-- Top 10
('Konnor', 'Griffin', 'SS'),
('Kevin', 'McGonigle', 'SS'),
('Nolan', 'McLean', 'SP'),
('Jesus', 'Made', 'SS'),
('Colt', 'Emerson', 'SS'),
('Aidan', 'Miller', 'SS'),
('JJ', 'Wetherholt', '2B'),
('Samuel', 'Basallo', 'C'),
('Leo', 'De Vries', 'SS'),
('Max', 'Clark', 'CF'),

-- 11-25
('Carson', 'Benge', 'CF'),
('Bubba', 'Chandler', 'SP'),
('Carter', 'Jensen', 'C'),
('Trey', 'Yesavage', 'SP'),
('Sal', 'Stewart', '3B'),
('Walker', 'Jenkins', 'CF'),
('Bryce', 'Eldridge', '1B'),
('Luis', 'Pena', 'SS'),
('Thomas', 'White', 'SP'),
('Chase', 'DeLauter', 'RF'),
('Andrew', 'Painter', 'SP'),
('Eli', 'Willits', 'SS'),
('Connelly', 'Early', 'SP'),
('Rainiel', 'Rodriguez', 'C'),
('Robby', 'Snelling', 'SP'),

-- 26-50
('Kade', 'Anderson', 'SP'),
('Zyhir', 'Hope', 'RF'),
('Payton', 'Tolle', 'SP'),
('Ryan', 'Sloan', 'SP'),
('Jonah', 'Tong', 'SP'),
('Edward', 'Florentino', 'OF'),
('Sebastian', 'Walcott', 'SS'),
('Dylan', 'Beavers', 'LF'),
('Mike', 'Sirota', 'OF'),
('Bryce', 'Rainer', 'SS'),
('Josue', 'Briceno', 'C'),
('Joe', 'Mack', 'C'),
('Brody', 'Hopkins', 'SP'),
('Franklin', 'Arias', 'SS'),
('Eduardo', 'Quintero', 'CF'),
('Josue', 'De Paula', 'RF'),
('Alfredo', 'Duno', 'C'),
('AJ', 'Ewing', 'OF'),
('Ryan', 'Waldschmidt', 'LF'),
('Jett', 'Williams', 'CF'),
('Travis', 'Bazzana', '2B'),
('Caleb', 'Bonemer', '3B'),
('Owen', 'Caissie', 'RF'),
('Seth', 'Hernandez', 'SP'),
('Emmanuel', 'Rodriguez', 'OF'),

-- 51-75
('Aiva', 'Arquette', 'SS'),
('Gage', 'Jump', 'SP'),
('George', 'Lombard Jr.', 'SS'),
('Jarlin', 'Susana', 'SP'),
('Moises', 'Ballesteros', 'C'),
('Eduardo', 'Tait', 'C'),
('Ralphy', 'Velazquez', '1B'),
('Josuar', 'Gonzalez', 'SS'),
('Jaxon', 'Wiggins', 'SP'),
('Ethan', 'Holliday', '3B'),
('Joseph', 'Parker', 'SS'),
('Braden', 'Montgomery', 'RF'),
('River', 'Ryan', 'SP'),
('Carlos', 'Lagrange', 'SP'),
('Noah', 'Schultz', 'SP'),
('George', 'Klassen', 'SP'),
('Travis', 'Sykora', 'SP'),
('Carson', 'Williams', 'SS'),
('Luis', 'Perales', 'SP'),
('Liam', 'Doyle', 'SP'),
('Brandon', 'Sproat', 'SP'),
('Angel', 'Genao', 'SS'),
('Jonny', 'Farmelo', 'CF'),
('Harry', 'Ford', 'C'),
('Theo', 'Gillen', 'OF'),

-- 76-100
('Dax', 'Kilby', 'SS'),
('Lazaro', 'Montes', 'RF'),
('Caden', 'Scarborough', 'SP'),
('Justin', 'Crawford', 'OF'),
('Jhostynxon', 'Garcia', 'CF'),
('Ryan', 'Clifford', '1B'),
('Trey', 'Gibson', 'SP'),
('JR', 'Ritchie', 'SP'),
('Kaelen', 'Culpepper', 'SS'),
('Jeferson', 'Quero', 'C'),
('Juneiker', 'Caceres', 'RF'),
('Jack', 'Wenninger', 'SP'),
('Charlee', 'Soto', 'SP'),
('Rhett', 'Lowder', 'SP'),
('Alex', 'Freeland', 'SS'),
('Bo', 'Davidson', 'CF'),
('Logan', 'Henderson', 'SP'),
('Jacob', 'Reimer', '3B'),
('Charlie', 'Condon', '1B'),
('Arjun', 'Nimmala', 'SS'),
('Kendry', 'Chourio', 'SP'),
('Jurrangelo', 'Cijntje', 'SP'),
('Cam', 'Caminiti', 'SP'),
('Jimmy', 'Crooks', 'C'),
('Ethan', 'Salas', 'C'),

-- 101-150 (ESPN 101-200, top bubble prospects)
('Max', 'Anderson', '2B'),
('Tommy', 'Troy', '2B'),
('Wyatt', 'Sanford', 'SS'),
('Felnin', 'Celesten', 'SS'),
('Jefferson', 'Rojas', 'SS'),
('Brice', 'Matthews', '2B'),
('Zach', 'Ehrhard', 'RF'),
('Denzer', 'Guzman', 'SS'),
('Nate', 'George', 'CF'),
('Elian', 'Pena', 'SS'),
('Jose', 'Corniell', 'SP'),
('Gavin', 'Fien', '3B'),
('Christian', 'Oppor', 'SP'),
('Roc', 'Riggio', '2B'),
('Luke', 'Dickerson', 'SS'),
('JD', 'Dix', '2B'),
('Steele', 'Hall', 'SS'),
('Hagen', 'Smith', 'SP'),
('Jackson', 'Ferris', 'SP'),
('Termarr', 'Johnson', '2B'),
('Gabriel', 'Gonzalez', 'RF'),
('James', 'Tibbs III', 'RF'),
('Josh', 'Hammond', 'SS'),
('Devin', 'Fitz-Gerald', 'SS'),
('Demetrio', 'Crisantes', '2B'),
('Enrique', 'Bradfield Jr.', 'CF'),
('Kayson', 'Cunningham', 'SS'),
('Kevin', 'DeFrank', 'SP'),
('Esteban', 'Mejia', 'SP'),
('Winston', 'Santos', 'SP'),
('Luis', 'Hernandez', 'SS'),
('Blake', 'Mitchell', 'C'),
('Thayron', 'Liranzo', 'C'),
('Kruz', 'Schoolcraft', 'SP'),
('Xavier', 'Isaac', '1B'),
('Luke', 'Adams', '1B'),
('Ryan', 'Johnson', 'SP'),
('Quinn', 'Mathews', 'SP'),
('Ricky', 'Tiedemann', 'SP'),
('Tyler', 'Bremner', 'SP'),
('Elmer', 'Rodriguez', 'SP'),
('Kevin', 'Alcantara', 'CF'),
('Emil', 'Morales', 'SS'),
('Luis', 'De Leon', 'SP'),
('Michael', 'Arroyo', '2B'),
('Parker', 'Messick', 'SP'),
('Khal', 'Stephen', 'SP'),
('Michael', 'Forret', 'SP'),
('Roldy', 'Brito', 'CF'),
('Kyson', 'Witherspoon', 'SP'),
('Didier', 'Fuentes', 'SP');


-- ============================================================
-- 2. CG_PlayerNicknames
-- ============================================================
-- Link nicknames to players via subquery on (first_name, last_name).
-- These are the names most commonly heard in auction speech-to-text.

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'Bubba' FROM CG_Players WHERE first_name = 'Bubba' AND last_name = 'Chandler';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'JJ' FROM CG_Players WHERE first_name = 'JJ' AND last_name = 'Wetherholt';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'JR' FROM CG_Players WHERE first_name = 'JR' AND last_name = 'Ritchie';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'AJ' FROM CG_Players WHERE first_name = 'AJ' AND last_name = 'Ewing';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'JD' FROM CG_Players WHERE first_name = 'JD' AND last_name = 'Dix';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'Sal' FROM CG_Players WHERE first_name = 'Sal' AND last_name = 'Stewart';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'Manny' FROM CG_Players WHERE first_name = 'Emmanuel' AND last_name = 'Rodriguez';

INSERT IGNORE INTO CG_PlayerNicknames (player_id, nickname)
SELECT player_id, 'Moises' FROM CG_Players WHERE first_name = 'Moises' AND last_name = 'Ballesteros';


-- ============================================================
-- 3. CG_CardMakers - Additional Manufacturers
-- ============================================================
-- Only real manufacturers/brands that produce or produced baseball cards.
-- Note: Bowman is already seeded (owned by Topps/Fanatics).
-- Fleer (owned by Upper Deck), Donruss/Panini already seeded.

INSERT IGNORE INTO CG_CardMakers (name) VALUES
('Leaf'),
('Fleer'),
('Score'),
('Pacific'),
('Playoff'),
('Wild Card'),
('Fanatics'),
('Topps Finest'),
('Bowman Chrome'),
('Topps Chrome'),
('Topps Archives'),
('Topps Heritage'),
('Topps Tribute'),
('Topps Sterling'),
('Topps Inception'),
('Topps Definitive'),
('Topps Dynasty'),
('Topps Luminaries'),
('Topps Tier One'),
('Topps Triple Threads'),
('Topps Allen & Ginter'),
('Topps Gypsy Queen'),
('Topps Gallery'),
('Topps Fire'),
('Topps Gold Label'),
('Topps Museum Collection'),
('Topps Transcendent'),
('Topps Brooklyn Collection'),
('Topps 206'),
('Topps 582 Montgomery'),
('Bowman Draft'),
('Bowman Sapphire'),
('Bowman Sterling'),
('Bowman Inception'),
('Panini Prizm'),
('Panini Select'),
('Panini Donruss'),
('Panini Donruss Optic'),
('Panini Mosaic'),
('Panini Chronicles'),
('Panini Immaculate'),
('Panini National Treasures'),
('Panini Spectra'),
('Panini Contenders'),
('Panini Flawless'),
('Panini Origins'),
('Panini Obsidian'),
('Panini Revolution'),
('Upper Deck SP Authentic'),
('Upper Deck Goodwin Champions');


-- ============================================================
-- 4. CG_CardStyles - Expanded Product Lines, Variants, Colors
-- ============================================================
-- Existing: Chrome, Sapphire, Refractor, Heritage, Prizm, Select, Optic, Mosaic, Gallery, Stadium Club

INSERT IGNORE INTO CG_CardStyles (style_name) VALUES
-- Bowman/Topps product lines
('1st Bowman'),
('1st Bowman Chrome'),
('Draft'),
('Sterling'),
('Inception'),
('Definitive'),
('Tier One'),
('Triple Threads'),
('Dynasty'),
('Luminaries'),
('Transcendent'),
('Brooklyn Collection'),
('Museum Collection'),
('Gold Label'),
('Fire'),
('Allen & Ginter'),
('Gypsy Queen'),
('Archives'),
('Opening Day'),
('Series 1'),
('Series 2'),
('Update'),
('Holiday'),
('Bowman Paper'),
('Bowman Chrome'),
('Bowman Sapphire'),
('Bowman Draft'),
('Bowman Sterling'),
('Bowman Inception'),
('Bowman Best'),
('Bowman Platinum'),
('Chrome Sapphire'),
('Finest'),
('Tribute'),
('582 Montgomery'),
('T206'),
('T205'),

-- Color parallels (most commonly called out in auctions)
('Blue'),
('Green'),
('Gold'),
('Orange'),
('Red'),
('Black'),
('Purple'),
('Pink'),
('Aqua'),
('Yellow'),
('Neon Green'),
('Sky Blue'),
('Fuchsia'),
('Rose Gold'),
('Platinum'),
('Silver'),
('White'),
('Teal'),
('Magenta'),
('Camo'),
('Ice'),
('Sepia'),

-- SuperFractor and numbered parallels
('SuperFractor'),
('X-Fractor'),
('Blue X-Fractor'),
('Black X-Fractor'),
('Aqua X-Fractor'),

-- Pattern / texture variants
('RayWave'),
('Lava'),
('Red Lava'),
('Geometric'),
('Wave'),
('Speckle'),
('Atomic'),
('Shimmer'),
('Gold Shimmer'),
('Orange Shimmer'),
('Blue Shimmer'),
('Aqua Shimmer'),
('Mojo'),
('Pulsar'),
('Purple Pulsar'),
('Aqua Pulsar'),
('Mini-Diamond'),
('Reptilian'),
('Reptilian Orange'),
('Reptilian Red'),
('Green Grass'),
('Steel Metal'),
('Pearl'),
('Retrofractor'),
('Prism'),
('Hyper'),
('Blue Wave'),
('Green Wave'),
('Purple Wave'),
('Yellow Wave'),
('Orange Wave'),
('Black Wave'),
('Red Wave'),

-- Panini-specific styles
('Silver Prizm'),
('Gold Prizm'),
('Green Prizm'),
('Blue Prizm'),
('Red Prizm'),
('Black Prizm'),
('Neon Green Prizm'),
('Orange Prizm'),
('Purple Prizm'),
('Tie-Dye'),
('Disco'),
('Fast Break'),
('Red White Blue'),
('Choice'),
('Scope'),
('Holo'),
('Color Blast'),
('Downtown'),
('Kaboom'),
('No Huddle'),
('Checkerboard'),
('Snakeskin'),
('Laundry Tag'),
('Nebula'),
('Camo Prizm'),

-- Other common style terms heard in auctions
('Base'),
('Mini'),
('Jumbo'),
('Retail'),
('Hobby'),
('HTA'),
('Mega Box'),
('Blaster'),
('Fat Pack'),
('Cello'),
('Hanger'),
('Value Pack');


-- ============================================================
-- 5. CG_CardSpecialties - Expanded Card Types
-- ============================================================
-- Existing: Die Cut, Booklet, Insert, Case Hit, Foil, Holographic,
--           Printing Plate, Autograph, Relic, Numbered

INSERT IGNORE INTO CG_CardSpecialties (name) VALUES
-- Relic / Memorabilia types
('Patch'),
('Jersey'),
('Jersey Relic'),
('Bat Relic'),
('Game-Used'),
('Game-Used Bat'),
('Game-Used Jersey'),
('Dual Relic'),
('Triple Relic'),
('Quad Relic'),
('Nameplate'),
('Laundry Tag Relic'),
('Cleat Relic'),
('Button Relic'),
('Glove Relic'),
('Hat Relic'),
('Batting Glove'),
('Jumbo Patch'),
('Prime Patch'),
('Logo Patch'),
('Team Logo Patch'),
('MLB Silhouette Patch'),
('Player-Worn'),
('Event-Worn'),

-- Autograph types
('On-Card Auto'),
('Sticker Auto'),
('Auto Relic'),
('Auto Patch'),
('Auto Jersey'),
('Dual Auto'),
('Triple Auto'),
('Quad Auto'),
('Cut Signature'),
('Cut Auto'),
('Inscription Auto'),
('First Auto'),
('Rookie Auto'),
('Prospect Auto'),
('Buyback Auto'),

-- Card designation types
('Rookie Card'),
('RC'),
('Prospect'),
('Draft Pick'),
('1st Bowman'),
('First Bowman Chrome'),
('1st Chrome'),
('International'),
('Rookie Debut'),

-- Print run / rarity types
('Parallel'),
('Short Print'),
('SP'),
('Super Short Print'),
('SSP'),
('Ultra Short Print'),
('USP'),
('1/1'),
('One of One'),
('/5'),
('/10'),
('/25'),
('/50'),
('/75'),
('/99'),
('/100'),
('/150'),
('/199'),
('/250'),
('/299'),
('/499'),
('/999'),

-- Variation types
('Variation'),
('Photo Variation'),
('Image Variation'),
('SP Variation'),
('SSP Variation'),
('Color Swap'),
('Missing Nameplate'),
('Throwback'),
('Retro'),

-- Base and common terms
('Base'),
('Base Auto'),
('Base Relic'),
('Refractor'),
('Chrome Refractor'),
('Mini'),
('Sparkle'),
('Foilboard'),
('Clear'),
('Acetate'),
('Canvas'),
('Silk'),
('Wood'),
('Metal'),
('Leather'),
('Cracked Ice'),

-- Special hits
('Superfractor'),
('Logoman'),
('Logo Man'),
('Shield'),
('MLB Shield'),
('Tag'),
('Laundry Tag'),
('Jumbo'),
('Oversized'),
('Boxloader'),
('Box Topper'),

-- Set-specific insert names heard in auctions
('Atomic'),
('Mojo'),
('Shimmer'),
('Speckle'),
('Wave'),
('Lava'),
('X-Fractor'),
('Pearl'),
('Sapphire'),
('Gold Vinyl'),
('Red Ink'),
('Blue Ink'),
('Green Ink'),
('Purple Ink'),
('Orange Ink'),

-- Multi-card / combo types
('Dual Player'),
('Triple Player'),
('Combo'),
('Franchise'),
('Letterman'),
('Letter Patch'),

-- Grading-related (commonly mentioned in auction context)
('Raw'),
('Graded'),
('PSA 10'),
('PSA 9'),
('BGS 9.5'),
('BGS 10'),
('SGC 10'),
('CGC 10'),
('Gem Mint'),
('Pristine'),
('Slab'),

-- Condition / packaging terms
('Sealed'),
('Factory Sealed'),
('Pack Fresh'),
('Case Fresh'),
('COMC'),
('Redemption'),
('Unredeemed');
